### ISSUE TITLE
 No module named 'ubl.const'; 'ubl' is not a package error

### ISSUE THREAD

**Issue by ghost** [arskom/pyubl#2]
I try for Turkey invoice UBL xml giving following error
Türkiye E-fatura için denemek istedim fakat aşadğıdaki hatayı verdi.

```
Traceback (most recent call last):
  File "./ubl.py", line 39, in <module>
    from ubl.const.schema.parsed import xmldsig
  File "/opt/fatura/ubl.py", line 39, in <module>
    from ubl.const.schema.parsed import xmldsig
ImportError: No module named 'ubl.const'; 'ubl' is not a package
```

**Comment by plq** [comment]
this is an installation error.

**Comment by bumblebeey** [comment]
how can i install correctly ?
